#!/usr/bin/sh
# vi: ft=sh
# By Chrystian "Kenielf"
VER="1.0.0"

# Functions
usage() {
    printf "\x1b[34m%s\x1b[0m: %s [--force | -f]\n" "${VER}" "${0}"
    printf " --force\tForces the confirmation queries\n"
    printf "  -f\t\tSame as -f\n"
    printf "Created by Chrystian M. F.\n"
}

get_yaycache() {
    du -bc $HOME/.cache/yay/* --exclude="completion.cache" --exclude="vcs.json" | \
        tail -n1 | \
        awk '{print $1}' | \
        numfmt --to=iec-i --suffix=B --format='%9.2f' | \
        tr -d ' '
}

# Defaults
b_force=false
installation_f="/$HOME/.knoxarch"
global_installation_f="/usr/share/knoxarch"

# Development
installation_f="$(pwd)"
# Arguments
while [ $# -gt 0 ]; do
    case $1 in
        --force|-f)
            b_force=true
            shift
            ;;
        --help|-h)
            usage && exit 0
            ;;
        *)
            printf "\x1b[31mArgumento Inválido!\x1b[0m\n" && \
                usage && exit 1
            ;;
    esac
done

# Main

cache_s="$(get_yaycache)"
if [ $b_force = true ]; then
    # Update the repo
    if [ -d "$installation_f" ]; then
        cd "$installation_f" && \
            git pull >/dev/null
        cd - || exit
    elif [ -d "$global_installation_f" ]; then
        cd "$global_installation_f" && \
            git pull >/dev/null
        cd - || exit
    fi
    # Update System
    yay -Syyuu --noconfirm && \
        paccache -r -k 1 && \
        printf "N\nN\nY" | yay -Scc >/dev/null && \
        printf "\x1b[32mRemoved \x1b[33m%s\x1b[32m of aur package cache files.\x1b[00m\n" "${cache_s}"
else
    # Update the repo
    if [ -d "$installation_f" ]; then
        cd "$installation_f" && \
            git pull >/dev/null
        cd - || exit
    elif [ -d "$global_installation_f" ]; then
        cd "$global_installation_f" && \
            git pull >/dev/null
        cd - || exit
    fi
    # Update System
    yay -Syyuu && \
        paccache -r -k 1 && \
        printf "N\nN\nY" | yay -Scc >/dev/null && \
        printf "\x1b[32mRemoved \x1b[33m%s\x1b[32m of aur package cache files.\x1b[00m\n" "${cache_s}"
fi
